### ISSUE TITLE
Nav bar illisible

### ISSUE THREAD

**Issue by GuillaumeASSIER** [BecauseOfProg/blog-v3#1]
Hello,
J'ai remarqué que votre barre est illisible lorsque que l'on descend dans la page. Le texte étant blanc, c'est très désagréable.
Pour illustrer mes propos :
En haut de la page c'est lisible
![image](https://user-images.githubusercontent.com/18405490/82937031-c277eb00-9f8f-11ea-8ac3-ce4c80481ea4.png)
Et quand on descend dans la plage la nav barre perds en lisibilité.
![image](https://user-images.githubusercontent.com/18405490/82936750-55fcec00-9f8f-11ea-8b1a-799d866d092a.png)

**Comment by theovidal** [comment]
Bien vu, nous nous posions également la question du style de cette barre.
Nous songions à un effet de flou afin de pouvoir refléter la page en dessous tout en assurant la lisibilité de cette barre.
Merci pour avoir relevé ce problème 😉

**Comment by theovidal** [comment]
Résolu sur la branche develop (fde1db6)
